/**
 * AUTO-GENERATED by npm run assets:manifest — do not edit by hand.
 * Source: extension/assets/kanye/
 */
(function (root) {
  root.FAA_KANYE_IMAGES = [];
})(typeof window !== 'undefined' ? window : globalThis);
