/**
 * AUTO-GENERATED by npm run assets:manifest — do not edit by hand.
 * Source: extension/assets/kanye/
 */
(function (root) {
  root.FAA_KANYE_IMAGES = [
  "1.jpg",
  "10.jpg",
  "2.jpg",
  "3.jpg",
  "4.jpg",
  "5.jpg",
  "6.jpg",
  "7.jpg",
  "8.jpg",
  "9.jpg"
];
})(typeof window !== 'undefined' ? window : globalThis);
